# Generated by Django 4.2.2 on 2024-06-04 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0019_alter_homepage_options_alter_homepage_banner2_course_and_more'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(to='article.course', verbose_name='دوره های کاربر'),
        ),
    ]
