# Generated by Django 4.2.2 on 2024-04-02 11:44

import article.models.video
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('position', models.IntegerField(default=1, verbose_name='پوزیشن')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('status', models.BooleanField(default=False, verbose_name='وضعیت انتشار')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی ها ',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='عنوان دوره')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('publish_status', models.CharField(choices=[('completed', 'تکمیل شده'), ('inprogress', 'درحال تکمیل')], default='inprogress', max_length=15, verbose_name='وضعیت انتشار دوره')),
                ('is_active', models.BooleanField(verbose_name='دوره منتشر شود')),
                ('is_free', models.BooleanField(default=False, verbose_name='دوره رایگان است')),
                ('price', models.PositiveIntegerField(blank=True, help_text='به تومان', null=True, verbose_name='هزینه دوره')),
                ('image', models.ImageField(upload_to='thumbnails/', verbose_name='تصویر')),
                ('slug', models.SlugField(help_text='slug', unique=True, verbose_name='نامک')),
                ('prerequisite', models.TextField(blank=True, null=True, verbose_name='پیش نیاز های دوره')),
                ('time_of_course', models.DurationField(help_text='HH:MM:SS', verbose_name='مدت زمان دوره')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('publish_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('SuggestedCourses', models.ManyToManyField(blank=True, to='article.course', verbose_name='دوره پیشنهادی')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='مدرس')),
                ('category', models.ManyToManyField(related_name='articles', to='article.category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'دوره ',
                'verbose_name_plural': 'دوره ها',
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.FloatField(blank=True, default=1, null=True, verbose_name='ترتیب ')),
                ('episode', models.IntegerField(blank=True, default=1, null=True, verbose_name='قسمت')),
                ('season', models.IntegerField(blank=True, default=1, null=True, verbose_name='فصل')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان فیلم')),
                ('video_description', models.CharField(blank=True, max_length=500, null=True)),
                ('slug', models.SlugField(max_length=255)),
                ('publish', models.BooleanField(default=False, verbose_name=' انتشار')),
                ('is_free', models.BooleanField(default=False, verbose_name=' رایگان')),
                ('duration', models.DurationField(blank=True, help_text='HH:MM:SS', null=True, verbose_name='مدت زمان ویدیو')),
                ('videofile', models.FileField(null=True, upload_to=article.models.video.video_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mkv'])], verbose_name='ویدیو')),
                ('video_thumbnail', models.ImageField(blank=True, null=True, upload_to=article.models.video.video_path, verbose_name='تامبنیل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='article.course', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'ویدیو',
                'verbose_name_plural': 'ویدیو ها ',
            },
        ),
    ]
