# Generated by Django 4.2.2 on 2024-04-02 12:16

import article.models.video
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='episode',
        ),
        migrations.RemoveField(
            model_name='videos',
            name='season',
        ),
        migrations.AlterField(
            model_name='videos',
            name='videofile',
            field=models.FileField(help_text='.mp4, .mkv', null=True, upload_to=article.models.video.video_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mkv'])], verbose_name='ویدیو'),
        ),
    ]
