# Generated by Django 4.2.2 on 2024-04-11 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_remove_videos_episode_remove_videos_season_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.FloatField(blank=True, default=2, null=True, verbose_name='ترتیب آزمون ')),
                ('slug', models.SlugField(max_length=255)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizes', to='article.course', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'آزمون',
                'verbose_name_plural': 'آزمون ها ',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان سوال')),
                ('question', models.TextField(null=True, verbose_name='سوال')),
                ('op1', models.CharField(max_length=200, null=True, verbose_name='گزینه اول')),
                ('op2', models.CharField(max_length=200, null=True, verbose_name='گزینه دوم')),
                ('op3', models.CharField(max_length=200, null=True, verbose_name='گزینه سوم')),
                ('op4', models.CharField(max_length=200, null=True, verbose_name='گزینه چهارم')),
                ('ans', models.CharField(choices=[('op1', 'گزینه اول '), ('op2', 'گزینه دوم '), ('op3', 'گزینه سوم '), ('op4', 'گزینه چهارم ')], max_length=200, null=True, verbose_name='پاسخ')),
                ('is_published', models.BooleanField(default=True, verbose_name='آیا منتشر شود')),
                ('position', models.FloatField(blank=True, default=1, null=True, verbose_name='ترتیب سوالات ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.quiz', verbose_name='آزمون')),
            ],
            options={
                'verbose_name': 'سوال',
                'verbose_name_plural': 'سوال ها ',
            },
        ),
    ]
