# Generated by Django 4.2.2 on 2024-04-11 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_quiz_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='position',
            field=models.FloatField(blank=True, default=1, null=True, verbose_name='ترتیب آزمون '),
        ),
    ]
