# Generated by Django 4.2.2 on 2024-04-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_quiz_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='title',
        ),
        migrations.AddField(
            model_name='quiz',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان آزمون'),
        ),
    ]
