# Generated by Django 4.2.2 on 2024-04-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_quiz_type_videos_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='type',
            field=models.CharField(default='quiz', editable=False, max_length=10, verbose_name='نوع'),
        ),
    ]
