# Generated by Django 4.2.2 on 2024-04-11 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_alter_videos_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='is_published',
            new_name='publish',
        ),
        migrations.AddField(
            model_name='quiz',
            name='publish',
            field=models.BooleanField(default=True, verbose_name='آیا منتشر شود'),
        ),
    ]
