# Generated by Django 4.2.2 on 2024-04-14 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0009_rename_is_published_question_publish_quiz_publish'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corrects', models.PositiveIntegerField(default=0, verbose_name='درست ها')),
                ('incorrects', models.PositiveIntegerField(default=0, verbose_name='درست ها')),
                ('total_score', models.PositiveIntegerField(default=0, verbose_name='امتیاز کل')),
                ('is_done', models.BooleanField(default=False, verbose_name='آزمون انجام شده است؟')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.quiz', verbose_name='آزمون')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
    ]
