# Generated by Django 4.2.2 on 2024-04-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0011_alter_question_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizprofile',
            name='choices',
            field=models.JSONField(blank=True, null=True, verbose_name='گزینه های انتخاب شده توسط کاربر'),
        ),
    ]
