# Generated by Django 4.2.2 on 2024-04-30 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_quizprofile_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizprofile',
            name='choices',
        ),
    ]
