# Generated by Django 4.2.2 on 2024-05-01 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0016_rename_test_mytestclass'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyTestClass',
        ),
    ]
