# Generated by Django 4.2.2 on 2024-05-22 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0017_delete_mytestclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان فیلم')),
                ('image', models.ImageField(upload_to='homepageheader/', verbose_name='تصویر header')),
                ('description', models.TextField(verbose_name='عنوان فیلم')),
                ('banner_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان بنر')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='banner/', verbose_name='تصویر header')),
                ('banner2_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان بنر')),
                ('banner2_image', models.ImageField(blank=True, null=True, upload_to='banner/', verbose_name='تصویر header')),
                ('banner2_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banner_2', to='article.course', verbose_name='دوره')),
                ('banner_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banner_1', to='article.course', verbose_name='دوره')),
            ],
            options={
                'verbose_name': 'خانه',
            },
        ),
    ]
