# Generated by Django 4.2.2 on 2024-06-04 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0018_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'خانه', 'verbose_name_plural': 'خانه'},
        ),
        migrations.AlterField(
            model_name='homepage',
            name='banner2_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banner_2', to='article.course', verbose_name='دوره یک '),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='banner_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banner_1', to='article.course', verbose_name=' دوره دو'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='description',
            field=models.TextField(verbose_name='توضیحات سایت'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان سایت'),
        ),
    ]
